### ISSUE TITLE
Can we have the app that show libadwaita prototypes ?

### ISSUE THREAD

**Issue by alcapitan** [allaeddineomc/adwaita-svg#1]
We could have the app with flatpak.
It would be useful to have what makes these svgs.
Sorry if an application like this already exists.

**Comment by allaeddineomc** [comment]
i don't really got it but from what i understand you are talking about something like glade and cambalache 
https://flathub.org/apps/details/ar.xjuan.Cambalache
https://flathub.org/apps/details/org.gnome.Glade
